# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cannula', '0028_auto_20230426_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='gbvToolB',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('fd1_26', models.CharField(verbose_name='7.1 Provider obtains written  or verbal informed consent (or informed assent from minors),  including explaining to the patient what the History and Examination form and police form entails and how resulting information may be used, prior to medical examination or procedure', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_27', models.CharField(verbose_name='7.2 Provider obtains written or verbal consent for HIV counseling and testing', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_28', models.CharField(verbose_name='7.3 Provider follows national or facility guidelines for obtaining informed assent from children and adolescents if patient is under age of maturity', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_29', models.CharField(verbose_name='7.4 Provider never forces the patient, including children of any age, to undergo an examination against her/his will, unless the examination is necessary for medical treatment ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_30', models.CharField(verbose_name='7.5 Provider makes it clear to the patient that s/he can decline any component of the examination or counseling session at any point, and seeks verbal consent at each stage of the examination', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_31', models.CharField(verbose_name='7.6 Provider respects the patient’s decision about whether to involve the police at all times, if in accordance with national law', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_32', models.CharField(verbose_name='7.7 If police involvement is legally mandated (e.g. for a minor), provider informs the patient or guardian about required procedures, patient rights, and possible outcomes of police involvement.as early in the discussion as possible', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_33', models.CharField(verbose_name='7.8 After the child’s safety has been secured and acute clinical care has been provided, if required by law, provider makes any mandated reports to authorities. This decision is guided by the least harmful course of action that takes into account the best interests of the child and his/her right to protection', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_34', models.CharField(verbose_name='8.1 Provider assesses and documents vital signs', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_35', models.CharField(verbose_name='8.2 Provider ensures patient is medically stabilized and treats serious injuries immediately ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_36', models.CharField(verbose_name='8.3 Provider takes a detailed medical history, as appropriate, from the patient (or from guardian/trusted companion if patient is unable to give a history and has consented to a companion being present, or the patient is a minor) ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_37', models.CharField(verbose_name='8.4 Provider manages genital and anal injuries appropriately (e.g., sutures deep vaginal, cervical, or anal lacerations or refers to higher-level facility if indicated, particularly in cases of female genital mutilation)', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_38', models.CharField(verbose_name='8.5 Provider manages minor injuries appropriately, after forensic evidence is collected (only if patient has given informed consent for collection of forensic evidence) (SEE STANDARD 19)', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_39', models.CharField(verbose_name='9.1 Provider demonstrates knowledge of empathetic and appropriate communication skills to use with all patients', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_40', models.CharField(verbose_name='10.1.1 Provider contacts a trained social worker or Family and child protection unit to be present throughout the examination and during any interaction with law enforcement', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_41', models.CharField(verbose_name='10.2 Provider offers compassionate, supportive counseling prior to history taking', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_42', models.CharField(verbose_name='10.3 If provider suspects home environment is abusive or dangerous, provider works to identify alternative shelter or appropriate course of action for child', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_43', models.CharField(verbose_name='10.4 For child patients, provider uses child-friendly communication techniques.', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_44', models.CharField(verbose_name='10.5 Provider permits child to have a trusted companion present during the exam, recognizing the companion may or may not be the caregiver or parent ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_45', models.CharField(verbose_name='10.6 To avoid pain or serious injury, provider does not use a speculum to examine pre-pubertal girls, unless an internal vaginal injury or internal bleeding is suspected— in which case general anesthesia is administered prior to exam and a child-sized, small speculum is used', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_46', models.CharField(verbose_name='10.7 Facility has child-appropriate dolls, toys or drawing supplies (paper, crayon/marker/pencil/paint) available ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_47', models.CharField(verbose_name='11.1 Provider does not share any information regarding the patient or the violent incident(s) with anyone who is not directly involved in the patient’s care', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_48', models.CharField(verbose_name='11.2 Provider allows only authorized people into the consultation or exam (e.g., authorized people could be patient’s preferred companion or staff involved in the patient’s care)', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_49', models.CharField(verbose_name='11.3 Provider gives patient adequate time, space, and privacy in order to undress and dress for exams ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_50', models.CharField(verbose_name='11.4 Facility keeps patient files, medico-legal forms, GBV register, forensic evidence and any other documents with identifying information about the patient securely in a locked cupboard, locker or locked room, according to national guidelines and facility protocols', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_51', models.CharField(verbose_name='11.5 Facility has a written SOP in place to govern who can access patient files, medico-legal forms, and forensic evidence', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_52', models.CharField(verbose_name='12.1 Provider takes care to minimize pain during exam ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_53', models.CharField(verbose_name='12.2 Provider gives pain relief medication when requested or as necessary', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_54', models.CharField(verbose_name='12.3 Provider keeps patient’s body covered with gown or sheet as much as possible throughout exam, so as to avoid unnecessary or traumatic bodily exposure', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_55', models.CharField(verbose_name='12.4 Facility offers patient the choice of the sex of the provider to conduct the examination. If provider of preferred sex is not available, facility offers the patient to have a staff member of the same sex present in the examination room', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_56', models.CharField(verbose_name='12.5 Facility offers inpatients and those staying in the on-site shelter/safe room simple food and fluids (to be given after medico-legal exam if patient has consented to one)', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_57', models.CharField(verbose_name='13.1 Provider documents findings from medical examination and treatment in patient’s record  as complete and detailed manner as possible including document injuries on a body map/ pictogram/ traumagram, and observation and documentation of any petechiae  on the scalp, behind ears, in the mouth, and in the sclera of eyes', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_58', models.CharField(verbose_name='13.2 Provider uses speculum only when appropriate and only if the provider has been trained on its proper use', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_59', models.CharField(verbose_name='13.3 If patient has been strangled or choked, provider tells patient to return to the clinic if experiencing any new onset of: difficulty breathing, voice changes, or signs of respiratory distress up to 72 hours after the assault, as this may be related to possible swelling in the tissue surrounding the trachea', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_60', models.CharField(verbose_name='13.4 If patient is experiencing heavy or prolonged anal bleeding, trained provider uses anoscope for anal exam, or refers patient to higher level facility.', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_61', models.CharField(verbose_name='14.1 Provider offers oral emergency contraception (EC) within 5 days (120 hours) of the assault, according to national guidelines', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_62', models.CharField(verbose_name='14.2 If oral EC is not available, and if it is appropriate, a trained provider offers to insert a copper-bearing intrauterine device (IUCD) only if the patient is seeking ongoing pregnancy prevention', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_63', models.CharField(verbose_name='14.3 If IUCD is selected, a provider trained in IUCD insertion inserts it within 120 hours (5 days) of sexual assault', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_64', models.CharField(verbose_name='14.4 If patient declines EC, provider gives information that EC is less effective as time passes, and emphasizes the importance of returning back to the facility for follow-up pregnancy testing, referral feedback and monitoring', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
            ],
        ),
        migrations.CreateModel(
            name='gbvToolC',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('fd1_65', models.CharField(verbose_name='15.1 For sexual assault survivors, provider offers HIV counseling and testing as per national guidelines', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_66', models.CharField(verbose_name='15.2 If the patient tests negative for HIV and the assault occurred within the past 72 hours, provider discusses the various risk factors for HIV infection with the patient to determine the patient’s need for PEP', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_67', models.CharField(verbose_name='15.3 If patient tests negative for HIV AND the sexual assault occurred within previous 72 hours, provider offers full 28 day dosage of PEP in a two or three-drug regimen, or in accordance with national guidance', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_68', models.CharField(verbose_name='15.4 If patient is a child and tests HIV negative, provider prescribes appropriate pediatric PEP dosage according to national guidance', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_69', models.CharField(verbose_name='15.5 If PEP is given, provider counsels on side effects, the importance of adherence, and the importance of completing the full course of treatment to ensure PEP effectively reduces the risk for HIV infection', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_70', models.CharField(verbose_name='15.6 If PEP is given, facility has a tracking and follow-up system in place for ensuring and documenting PEP regimen completion ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_71', models.CharField(verbose_name='15.7 If patient tests positive for HIV and is interested in disclosing status to partner or family members, provider assesses for IPV and offers tailored guidance on how to disclose patient’s HIV status to avoid disclosure-related violence, without pressuring patient to disclose', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_72', models.CharField(verbose_name='15.8 If patient refuses an HIV test and serostatus is unknown, and assault occurred within previous 72 hours, provider still offers PEP and encourages patient to return for HIV counseling and testing', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_73', models.CharField(verbose_name='16.1 Provider offers prophylaxis or treatment for sexually transmitted infections (STIs), and the choice of drugs and regimens follows national guidelines', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_74', models.CharField(verbose_name='16.2 Provider gives tetanus vaccination if patient has not had one in past ten years, or is uncertain about vaccination status', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_75', models.CharField(verbose_name='16.3 Provider gives Hepatitis B vaccination within 24 hours of assault if the patient is not already immune (determined through a blood test) according to the national guidelines', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_76', models.CharField(verbose_name='17.1 Provider offers basic counseling including active listening, empathy, reassurance, and identification of social support ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_77', models.CharField(verbose_name='17.2 Providers with a good understanding of violence deliver mental health care to patients, according to national guidelines ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_78', models.CharField(verbose_name='17.3 Provider offers referrals to long-term mental health care and/or support groups', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_79', models.CharField(verbose_name='18.1 Provider conducts forensic examination and evidence collection IF the following are in place', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_80', models.CharField(verbose_name='18.2 Provider who has been trained in forensics takes a detailed forensic history as appropriate from the patient or guardian', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_81', models.CharField(verbose_name='18.3 Provider who has been trained in forensics collects and documents appropriate evidence (in addition to documentation of injuries above) within 5 days of sexual assault or at any time during the cycle of interpersonal violence, based upon the patient’s history', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_82', models.CharField(verbose_name='19.1 Provider is aware of the importance of forensic evidence collection as evidence to present in a criminal case', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_83', models.CharField(verbose_name='19.2 Providers use a standard protocol, checklist or kit to collect, package and seal forensic evidence correctly, and store it securely', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_84', models.CharField(verbose_name='19.3 Provider is aware of frequently-observed patterns of bruising, laceration and abrasion that are indicative of GBV', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_85', models.CharField(verbose_name='19.4 Provider asks questions to clarify his or her understanding when there are injuries or patterns observed that do not match the medical or forensic history', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_86', models.CharField(verbose_name='19.5 Provider wears clean gloves throughout the evidence collection process and changes gloves frequently when examining different body areas and between patients to avoid contamination', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_87', models.CharField(verbose_name='19.6 Provider collects forensic evidence within 5 days of the assault, since the likelihood of obtaining viable specimens decreases over time', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_88', models.CharField(verbose_name='19.7 When collecting specimens for medical testing and forensic samples, provider collects forensic samples first since there is an increased likelihood of obtaining biologic materials within the first specimens collected', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_89', models.CharField(verbose_name='19.8 Provider maintains chain of custody  for appropriate and secure collection, storage, and transfer of evidence, including forensic photodocumentation', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_90', models.CharField(verbose_name='19.9 Facility has systems in place to minimize the number of people who handle the evidence to maintain the chain of custody', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_91', models.CharField(verbose_name='19.10 Facility has systems in place to support and build the capacity of the provider to testify in court, if called upon to do so', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_92', models.CharField(verbose_name='19.11 If patient gives consent, the provider offering care documents injuries with photographs and ruler, taken with a good quality camera with flash, explaining that these pictures are for the confidential use of the facility to ensure patient receives the most appropriate clinical care, or for use in court and will not be shared publicly or at trial', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_93', models.CharField(verbose_name='20.1 Provider tells the patient about other available services and makes written referrals to the following services if relevant and wanted by the patient (including community-based services):', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_94', models.CharField(verbose_name='20.2 If facility does not have a functioning laboratory, provider offers a referral to a nearby laboratory (for blood and pregnancy tests, etc.)', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_95', models.CharField(verbose_name='20.3 Facility has a system in place to document referral linkage(s) through confirmation with the referral facility, patient, referral card system or other method', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_96', models.CharField(verbose_name='20.4 Facility informs stakeholders (police, community organizations, etc.) about the GBV services that are available at the facility, and during what hours they are provided. Facility makes clear that all survivors are welcome, and that seeking GBV care does not mean the survivor will have to pursue a legal case', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_97', models.CharField(verbose_name='20.5 Facility has a list of support services that have been mapped at the local, district and provincial/state levels, and this referral directory is available for on-site review', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_98', models.CharField(verbose_name='20.6 Facility updates the referral directory at least once per year by calling phone numbers and/or visiting locations, adding newly-available resources, and deleting resources that no longer exist', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_99', models.CharField(verbose_name='21.1 Provider gives as much information as possible and provides all necessary referrals to the patient on the initial visit, in case the patient does not return for follow-up', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_100', models.CharField(verbose_name='21.2 Facility has a system in place to follow up with patients', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_101', models.CharField(verbose_name='21.3 Provider or follow up team monitors the patient’s clinical condition and treatment including HIV and pregnancy test results, and provides counseling and support over time', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_102', models.CharField(verbose_name='21.4 Provider asks patient if s/he consents to follow up by phone or SMS text message, and documents a number where patient can be safely and privately contacted', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_103', models.CharField(verbose_name='21.5 Facility offers providers a budget, phone credit or mobile phone credit (airtime) to make follow-up phone calls or SMS text messages to patients who consent to being contacted this way', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_104', models.CharField(verbose_name='21.6 Facility has a focal point or team who help coordinate each patient’s care, treatment, follow-up and linkages with referral services ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_105', models.CharField(verbose_name='21.7 Provider and/or focal point follow up with the patient at time intervals according to national guidelines, or at a minimum, 1 month after assault and again at 2 months after assault ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_106', models.CharField(verbose_name='21.8 Provider encourages follow up visits through strategies including issuing appointment cards, phone call or SMS reminders, home visits, personal accompaniment to services if patient has consented to being contacted this way', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
            ],
        ),
        migrations.CreateModel(
            name='gbvToolD',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('fd1_107', models.CharField(verbose_name='22.1 Facility has at least  two  service providers trained in GBV', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_108', models.CharField(verbose_name='22.2 Providers receive training   relevant to their roles and responsibilities. Training should include critical GBV elements such as patient intake, informed consent and assent, first-line support, patient confidentiality and privacy, routine enquiry, documentation, PEP, EC, clinical examination, HTC, referrals, forensic, testifying in court', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_109', models.CharField(verbose_name='23.1 Facility has a supervision plan in place that results in the direct observation of at least one patient-provider interaction per year for each provider offering GBV care', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_110', models.CharField(verbose_name='23.2 Providers receive verbal or written feedback from a supervisor after each directly observed patient-provider interaction', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_111', models.CharField(verbose_name='23.3 Facility has at least one feedback mechanism for patients to anonymously report their level of satisfaction or any grievances with services, including any violation of her/his rights (e.g., regular patient satisfaction surveys, community feedback forum, suggestion box, ombudsman or phone helpline)', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_112', models.CharField(verbose_name='23.4 Facility ensures that all staff providing GBV care receive CME.  and expand competencies via an ongoing capacity-building plan with short, targeted skill-builders, regular team meetings, and other activities, and are supported on a personal level in this work', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_113', models.CharField(verbose_name='23.5 Facility has mechanisms in place to support and promote self-care  for providers who experience secondary trauma as a result of providing post-violence care', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_114', models.CharField(verbose_name='24.1 Facility has the following guidelines and documents available on-site for review', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_115', models.CharField(verbose_name='24.2 Providers know of and utilize these guidelines and documents', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_116', models.CharField(verbose_name='25.1 Facility works with other services to integrate GBV enquiry and care into their programs (e.g., HIV, antenatal care, family planning counseling, etc.) ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_117', models.CharField(verbose_name='25.2 Facility has a community liaison to raise awareness of GBV and the services that are available OR facility conducts outreach in local communities to raise awareness', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_118', models.CharField(verbose_name='26.1 Provider collects and documents the following information about a patient’s experience of GBV and the post-GBV care s/he received, if available', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_119', models.CharField(verbose_name='26.2 Provider fills medical records and forms completely with all relevant information (SEE CHART REVIEW TOOL FOR SCORING INSTRUCTIONS)', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_120', models.CharField(verbose_name='27.1 Providers have been trained in how to collect and enter data', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_121', models.CharField(verbose_name='27.2 Adherence to proper data collection methods is verified (e.g., supervisor periodically reviews a sample of charts to assess quality and consistency)', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_122', models.CharField(verbose_name='28.1 GBV data are disaggregated by sex (male and female)', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_123', models.CharField(verbose_name='28.2 GBV data are disaggregated by age in years  (0-4, 5-9, 10-14, 15-19, 20-24, 25-29, 30-49, 50-59, 60+)', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_124', models.CharField(verbose_name='28.3 GBV data are disaggregated by types of violence experienced and whether the perpetrator was an intimate partner or non-partner', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_125', models.CharField(verbose_name='28.4 GBV data includes the number of sexual assault survivors who received PEP at the facility within the 72 hour window', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_126', models.CharField(verbose_name='28.5 GBV data include the number of people who completed the PEP regimen', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_127', models.CharField(verbose_name='28.6 GBV service data  are linked to HIV and other health services data through common unique identifiers (such as a numeric code), a central filing system, or shared electronic medical records system', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_128', models.CharField(verbose_name='28.7 Data reports for GBV statistics (with no personal identifying information of patients) are available for sharing with management team, referral partners and other appropriate, relevant stakeholders, when safe and prudent to do so', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
                ('fd1_129', models.CharField(verbose_name='28.8 Improvement plans for service delivery are made after GBV data are reviewed, including changes or updates to the services offered, approaches used, and commodities procured', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')])),
            ],
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_1',
            field=models.CharField(verbose_name='1.1 Facility offers essential GBV care  24 hours a day OR facility helps patients to access alternative facilities that provide essential care during off-hours', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_10',
            field=models.CharField(verbose_name='3.2 Facility ensures that signs inside and outside the facility are discreet ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_11',
            field=models.CharField(verbose_name='3.3 Facilitys rooms/areas where GBV counseling and clinical services are provided are private ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_12',
            field=models.CharField(verbose_name='3.5 Facility has all essential infrastructure, furniture, equipment, supplies, documents, and commodities available ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_13',
            field=models.CharField(verbose_name='3.6 Facility has a system in place to check on a quarterly basis whether medicines, vaccines, and tests are within validity/expiration date, and safely discard those that have expired', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_14',
            field=models.CharField(verbose_name='3.7 Facility integrates essential GBV supplies, commodities, vaccines, tests and equipment (DETAILS IN BOX 1) within the facility’s essential supply chain', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_15',
            field=models.CharField(verbose_name='3.8 Facility has not had a stock-out of essential GBV supplies, vaccines, tests or medicines (DETAILS IN BOX 1) in the past three months, and there is a system in place for emergency orders', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_16',
            field=models.CharField(verbose_name='4.1 Active case identification If patient presents with common signs and symptoms for IPV or SV (SEE SIGNS AND SYMPTOMS IN BOX 2), the provider asks about IPV or SV (based on suspicion of violence)', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_17',
            field=models.CharField(verbose_name='4.2 Facility has a standard process to ask about IPV or SV (e.g., job aid, algorithm, etc.) which aligns with national guidelines', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_18',
            field=models.CharField(verbose_name='4.3 Facilitys policy is to conduct routine enquiry about IPV or SV ONLY IF services meet all of the following WHO minimum requirements for routine enquiry', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_19',
            field=models.CharField(verbose_name='5.2 Provider brings up topic of GBV carefully by making some general statements about GBV before asking patient directly about her/his situation', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_20',
            field=models.CharField(verbose_name='5.3 Provider does not require patient to talk about her/his experience of IPV or SV if s/he does not want to', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_21',
            field=models.CharField(verbose_name='5.4 Provider explains that s/he will ask the patient detailed questions to assess his or her safety and to make sure s/he gets the right treatment and support ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_22',
            field=models.CharField(verbose_name='5.5 Provider asks simple and direct questions about specific acts of violence to enquire about IPV or SV and documents responses', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_23',
            field=models.CharField(verbose_name='6.1 Provider  asks simple and direct questions to assess immediate danger to the patient’s life', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_24',
            field=models.CharField(verbose_name='6.2 If patient responds “yes” to 3 of the questions above concerning immediate danger, or if the patient requests shelter, the provider offers appropriate referrals to shelter or safe housing, or works with the patient to identify a safe place where s/he can go', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_25',
            field=models.CharField(verbose_name='6.3 Provider helps patient to make a safety plan', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_3',
            field=models.CharField(verbose_name='1.3 Facility keeps a copy of the History and examination form. Patients are  examined and treated with or without Police Form. Ask to see the form.', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_5',
            field=models.CharField(verbose_name='1.5 Facility eliminates or reduces fees for GBV patients', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_6',
            field=models.CharField(verbose_name='1.6 Facility prioritizes patients who have experienced sexual assault to ensure they receive care and support as soon as possible', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_7',
            field=models.CharField(verbose_name='1.7 Facility ensures all patients have equal access to care, regardless of sex,marital status, age, disability, race, religion, and  ethnicity', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_8',
            field=models.CharField(verbose_name='2.1 Facility has visible IEC materials for patients (e.g., posters and/or pamphlets on what to do in case of GBV, GBV laws and rights, and available services) in high-traffic areas ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtool',
            name='fd1_9',
            field=models.CharField(verbose_name='3.1 Facility offers GBV services in a location that is part of —or next to— a health facility ', max_length=4, default=None, choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')]),
        ),
        migrations.AddField(
            model_name='gbvtoold',
            name='rgbv_oid',
            field=models.ForeignKey(to='cannula.gbvTool'),
        ),
        migrations.AddField(
            model_name='gbvtoolc',
            name='rgbv_oid',
            field=models.ForeignKey(to='cannula.gbvTool'),
        ),
        migrations.AddField(
            model_name='gbvtoolb',
            name='rgbv_oid',
            field=models.ForeignKey(to='cannula.gbvTool'),
        ),
    ]
